### ISSUE TITLE
Why are you going up a directory?

### ISSUE THREAD

**Issue by Flammable-Duck** [Jeremys556/GroupchatBot#1]
I assume that this is to access  `botdata.json` but I wanted to make sure. If this is so, then why not:
1. use `with open("../botdata.json", "r") as f:` instead, or
2. just keep botdata.json in the same folder, so all your files are in the same place?

**Comment by Jeremys556** [comment]
It's to separate the bot data, and the token from the repository so it doesn't show up on the github, mainly. And since all the files are there, might as well just put all outside files there, to make it simple.

**Comment by Flammable-Duck** [comment]
If you don't want files to be tracked by git, you should use a gitignore file. Also, I believe it is best practice to use environment variables instead of a file for the token. I can make a pull request with that, if you like.
